In [1]:
import pandas as pd

In [2]:
import os
os.listdir('../data')

['banklist.csv',
 'billboard.csv',
 'concat_1.csv',
 'concat_2.csv',
 'concat_3.csv',
 'country_timeseries.csv',
 'gapminder.tsv',
 'genshin.csv',
 'genshin.xlsx',
 'hypernetwork_loss.csv',
 'pew.csv',
 'print_data.xls',
 'raw_data_urls.txt',
 'scientists.csv',
 'survey_person.csv',
 'survey_site.csv',
 'survey_survey.csv',
 'survey_visited.csv',
 'tesla_stock_quandl.csv',
 'weather.csv']

In [3]:
df = pd.read_excel('../data/genshin.xlsx')
df.head()

,character_name,rarity,region,vision,weapon_type,model,constellation,birthday,special_dish,affiliation,...,hp_1_20,atk_1_20,def_1_20,spsecial_0,special_1,special_2,special_3,special_4,special_5,special_6
0,Albedo,5,Mondstadt,Geo,Sword,Medium Male,Princeps Cretaceus,2023-09-13 00:00:00,Woodland Dream,Knights of Favonius,...,1030,20,68,0,0,0.072,0.144,0.144,0.216,0.288
1,Alhaitham,5,Sumeru,Dendro,Sword,Tall Male,Vultur Volans,2023-02-11 00:00:00,Ideal Circumstance,Sumeru Akademiya,...,1039,24,60,0,0,0.072,0.144,0.144,0.216,0.288
2,Aloy,5,NaN,Cryo,Bow,Medium Female,Nora Fortis,2023-04-04 00:00:00,Satiety Gel,Wandering Heroine,...,848,18,53,0,0,0.072,0.144,0.144,0.216,0.288
3,Amber,4,Mondstadt,Pyro,Bow,Medium Female,Lepus,2023-08-10 00:00:00,Outrider's Champion Steak!,Knights of Favonius,...,793,19,50,0,0,0.060,0.120,0.120,0.180,0.240
4,Arataki Itto,5,Inazuma,Geo,Claymore,Tall Male,Taurus Iracundus,2023-06-01 00:00:00,Way of the Strong,Arataki Gang,...,1001,18,75,0,0,0.048,0.096,0.096,0.144,0.192

In [5]:
df['character_name']

0           Albedo
1        Alhaitham
2             Aloy
3            Amber
4     Arataki Itto
          ...
67          Yaoyao
68           Yelan
69         Yoimiya
70         Yun Jin
71         Zhongli
Name: character_name, Length: 72, dtype: object