In [1]:
for i in range(1, 1000):
    print("레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!")

레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!
레일라... 넌 천재야.. 할 수 있잖아! 상처받지 말고! 나아가!

In [3]:
%pip install ebooklib

Collecting ebooklibNote: you may need to restart the kernel to use updated packages.

  Downloading EbookLib-0.18.tar.gz (115 kB)
     ---------------------------------------- 0.0/115.5 kB ? eta -:--:--
     -------------------------------------- 115.5/115.5 kB 7.0 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: lxml in c:\users\starl\anaconda3\lib\site-packages (from ebooklib) (4.9.2)
Requirement already satisfied: six in c:\users\starl\anaconda3\lib\site-packages (from ebooklib) (1.16.0)
Building wheels for collected packages: ebooklib
  Building wheel for ebooklib (setup.py): started
  Building wheel for ebooklib (setup.py): finished with status 'done'
  Created wheel for ebooklib: filename=EbookLib-0.18-py3-none-any.whl size=38802 sha256=f240e35d3af9e15b98b00ffbbe7d3de65926ef748bc5135fb94829ba68458c3c
  Stored in directory: c:\users\starl\appdata\local\pip\cache\wheels\65\2b\63\68307c736d5a2fafeebe9df3e5eccacfe892204ce1fd31a03c
Successfully built ebooklib
Installing collected packages: ebooklib
Successfully installed ebooklib-0.18

In [11]:
from ebooklib import epub

# 새로운 EPUB 책을 생성합니다
book = epub.EpubBook()

# 메타데이터를 설정합니다
book.set_identifier('id12345612991nncikk')
book.set_title('Sample book')
book.set_language('en')

book.add_author('Author Layla-focalors')

# 텍스트 파일을 읽습니다
text = "레일라는 평범한 소녀였습니다. 그러나 어느 날, 그녀는 자신의 마을이 고대 마법에 의해 저주받았음을 알게 되었습니다. 마을 사람들은 모두 돌로 변해버렸고, 레일라만이 살아남았습니다. 그녀는 저주를 풀기 위해 위험천만한 여행을 떠나기로 결심했습니다. 그녀의 여행은 신비한 숲을 통과하면서 시작되었습니다. 숲은 이상한 생물들로 가득 차 있었고, 그 중 일부는 레일라를 돕기 위해 나타났습니다. 그들은 그녀에게 마법의 지팡이를 주었고, 이 지팡이는 그녀가 앞으로 직면할 모든 위험을 극복하는 데 도움이 되었습니다. 레일라는 또한 높은 산을 오르고, 깊은 강을 건너며, 끝없는 사막을 통과하면서 여러 시련을 겪었습니다. 그러나 그녀는 결코 포기하지 않았고, 그녀의 용기와 결단력은 그녀를 계속 전진하게 만들었습니다. 결국, 레일라는 마지막으로 도전해야 할 곳, 고대 마법사의 성을 찾아냈습니다. 그녀는 성 안으로 들어가서 마법사와 대결했고, 그녀의 지팡이와 용기 덕분에 그를 이겼습니다. 마법사가 쓰러지자, 그의 저주는 풀렸고, 마을 사람들은 다시 원래의 모습으로 돌아왔습니다. 레일라의 여행은 그녀를 평범한 소녀에서 진정한 영웅으로 바꾸었습니다. 그녀는 저주를 풀고 마을을 구했지만, 무엇보다도 그녀는 자신의 용기와 결단력을 발견했습니다. 그녀의 이야기는 모험과 용기, 그리고 우정에 대한 이야기였습니다. 그리고 이제, 그녀의 이야기는 우리 모두에게 영감을 주는 전설이 되었습니다."
# 책에 새로운 페이지를 추가합니다
c1 = epub.EpubHtml(title='Chapter 1', file_name='chap_01.xhtml', lang='en')
c1.content = '<h1>Chapter 1</h1><p>' + text + '</p>'

# 책에 페이지를 추가합니다
book.add_item(c1)

# 목차를 생성합니다
book.toc = (epub.Link('chap_01.xhtml', 'Chapter 1', '1'),)

# EPUB 파일을 작성합니다
epub.write_epub('testmodel22.epub', book, {})

레일라는 평범한 소녀였습니다. 그러나 어느 날, 그녀는 자신의 마을이 고대 마법에 의해 저주받았음을 알게 되었습니다. 마을 사람들은 모두 돌로 변해버렸고, 레일라만이 살아남았습니다. 그녀는 저주를 풀기 위해 위험천만한 여행을 떠나기로 결심했습니다.

그녀의 여행은 신비한 숲을 통과하면서 시작되었습니다. 숲은 이상한 생물들로 가득 차 있었고, 그 중 일부는 레일라를 돕기 위해 나타났습니다. 그들은 그녀에게 마법의 지팡이를 주었고, 이 지팡이는 그녀가 앞으로 직면할 모든 위험을 극복하는 데 도움이 되었습니다.

레일라는 또한 높은 산을 오르고, 깊은 강을 건너며, 끝없는 사막을 통과하면서 여러 시련을 겪었습니다. 그러나 그녀는 결코 포기하지 않았고, 그녀의 용기와 결단력은 그녀를 계속 전진하게 만들었습니다.

결국, 레일라는 마지막으로 도전해야 할 곳, 고대 마법사의 성을 찾아냈습니다. 그녀는 성 안으로 들어가서 마법사와 대결했고, 그녀의 지팡이와 용기 덕분에 그를 이겼습니다. 마법사가 쓰러지자, 그의 저주는 풀렸고, 마을 사람들은 다시 원래의 모습으로 돌아왔습니다.

레일라의 여행은 그녀를 평범한 소녀에서 진정한 영웅으로 바꾸었습니다. 그녀는 저주를 풀고 마을을 구했지만, 무엇보다도 그녀는 자신의 용기와 결단력을 발견했습니다. 그녀의 이야기는 모험과 용기, 그리고 우정에 대한 이야기였습니다. 그리고 이제, 그녀의 이야기는 우리 모두에게 영감을 주는 전설이 되었습니다.

In [12]:
word = 'Layla'
sent = 'Layla is cute'

In [13]:
print(word[0])
print(sent[0])

L
L

In [14]:
sent[0:5]

'Layla'

In [15]:
sent[:]

'Layla is cute'

In [16]:
sent[:len(sent)]

'Layla is cute'

In [17]:
sent[-7:-3]

'is c'

In [18]:
sent[-3:]

'ute'

In [19]:
sent[:3]

'Lay'

In [20]:
sent[0:3]

'Lay'

In [21]:
sent[4:]

'a is cute'

In [23]:
sent[:]

'Layla is cute'

In [24]:
sent[::2]

'Lyai ue'

In [25]:
a = 'Name : Layla'
b = 'StudentID : 20230000'
c = 'Hobby : Study'
d = 'comment : Cute'
" ".join([a, b, c, d])

'Name : Layla StudentID : 20230000 Hobby : Study comment : Cute'

In [28]:
text = """Guard: What? Ridden en a horse?
Queen Raiden: Yes!
Guard: You're using coconuts!
Queen Raiden: What?
Guard: You're Got ... coconutes[s] and you;re banagin' em together
"""
str(text.splitlines()[::2])

'[\'Guard: What? Ridden en a horse?\', "Guard: You\'re using coconuts!", "Guard: You\'re Got ... coconutes[s] and you;re banagin\' em together"]'

In [29]:
str(text.splitlines()[::2]).replace('Guard', 'Yae Miko')

'[\'Yae Miko: What? Ridden en a horse?\', "Yae Miko: You\'re using coconuts!", "Yae Miko: You\'re Got ... coconutes[s] and you;re banagin\' em together"]'

In [30]:
'{} is cute!'.format('Layla')

'Layla is cute!'

In [31]:
"""{0}은 매우매우 착하고 귀엽고 사랑스럽습니다.
이 사악한 {1}은 {0}를 괴롭히는 원인 중 하나입니다.""".format('레일라', '나히다')

'레일라은 매우매우 착하고 귀엽고 사랑스럽습니다.\n이 사악한 나히다은 레일라를 괴롭히는 원인 중 하나입니다.'

In [32]:
"나히다는 {age}살 이상이다.".format(age=500)

'나히다는 500살 이상이다.'

In [33]:
"나는! {:,}살 까지 살고 싶다!".format(999999999999)

'나는! 999,999,999,999살 까지 살고 싶다!'

In [35]:
'소스코드의 숫자는 {0:.3}개 이며, {0:.3%}이 값들을 가진다.'.format(7/68790)

'소스코드의 숫자는 0.000102개 이며, 0.010%이 값들을 가진다.'

In [36]:
"my user id code is {:06d}".format(12)

'my user id code is 000012'

In [37]:
'my love number is %d' % 7

'my love number is 7'

In [41]:
'%(name)s is very cute, but her sleep time is %(time).2f' % {'name':'Layla', 'time':1.1631212}

'Layla is very cute, but her sleep time is 1.16'

In [42]:
name = '레일라'
month = 12
day = 19
f"{name}! {month}/{day} 생일 축하해!"

'레일라! 12/19 생일 축하해!'

In [45]:
import re
ax = re.match(pattern='\d{10}', string='1234567890')
ax

In [46]:
if(bool(ax)):
    print('match')
else:
    print('un match')

match

In [48]:
"match" if bool(ax) else "Unmatch"
# 3항 연산자

'match'

In [49]:
ax.start()

0

In [50]:
ax.end()

10

In [51]:
ax.group()

'1234567890'

In [52]:
ax.span()

(0, 10)

In [53]:
re.match(pattern='\d{3}\s\d{4}\s\d{4}', string='123 4567 8901')

In [54]:
re.match(pattern='\(\d{3}\)\s\d{3}\-\d{4}', string='(123) 456-7890')

In [57]:
re.match(pattern='\+\d{1}\s\d{3}\-\d{4}', string='+1 (123) 456-7890')

In [59]:
re.match(pattern='\+\d{1}\s\(\d{3}\)\s\-\d{4}', string='+1 (123) 456-7890')

In [60]:
re.match(pattern='\+\d\s\(\d{3}\)\s\d{3}\-\d{4}', string='+1 (123) 456-7890')

In [63]:
re.match(pattern='\+\d{1,3}\s\(\d{3}\)\s\d{3}\-\d{4}', string='+1 (123) 456-7890')

In [64]:
p = re.compile('\D{9}\:\d{4}')
p.match(string='localhost:8888')

In [65]:
p.groups

0

In [67]:
p = re.compile('\D{9}\:\d{4}')
p.match(string='localhost:8888').group()

'localhost:8888'

In [68]:
def my_exp(data):
    return data ** 2

In [69]:
def my_exp_c(data, n):
    return data ** n

In [70]:
import pandas as pd

In [71]:
df = pd.DataFrame({
    'a' : [10, 20, 30],
    'b' : [20, 30, 40]
})

In [72]:
df

    a   b
0  10  20
1  20  30
2  30  40

In [73]:
df['a'].apply(my_exp)

0    100
1    400
2    900
Name: a, dtype: int64

In [74]:
df['a'].transform(my_exp)

0    100
1    400
2    900
Name: a, dtype: int64

In [75]:
df['a'].agg(my_exp)

0    100
1    400
2    900
Name: a, dtype: int64

In [76]:
df ** 2

     a     b
0  100   400
1  400   900
2  900  1600

In [77]:
df['a'] ** 2

0    100
1    400
2    900
Name: a, dtype: int64

In [79]:
df['a'].transform(my_exp_c, n=10)

0        10000000000
1     10240000000000
2    590490000000000
Name: a, dtype: int64

In [80]:
printme = lambda x : print(x)

In [81]:
df.agg(printme, axis=0)

0    10
1    20
2    30
Name: a, dtype: int64
0    20
1    30
2    40
Name: b, dtype: int64

a    None
b    None
dtype: object

In [82]:
df.agg(printme, axis=1)

a    10
b    20
Name: 0, dtype: int64
a    20
b    30
Name: 1, dtype: int64
a    30
b    40
Name: 2, dtype: int64

0    None
1    None
2    None
dtype: object

In [83]:
df

    a   b
0  10  20
1  20  30
2  30  40

In [84]:
def my_mean(data, tm):
    sum = 0
    for i in data:
        sum += i
    if(tm == 0):
        return sum / df.shape[0]
    else:
        return sum / df.shape[1]

In [86]:
df.agg(my_mean, tm=0)

a    20.0
b    30.0
dtype: float64

In [87]:
df.agg(my_mean, tm = 1, axis = 1)

0    15.0
1    25.0
2    35.0
dtype: float64

In [90]:
import seaborn as sns

In [92]:
getNAN = lambda x : pd.isnull(x).sum()

df.apply(getNAN)

a    0
b    0
dtype: int64

In [93]:
df = sns.load_dataset("titanic")
df.apply(getNAN)

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [94]:
getNANP = lambda x : (pd.isnull(x).sum()) / len(x)
df.apply(getNANP)

survived       0.000000
pclass         0.000000
sex            0.000000
age            0.198653
sibsp          0.000000
parch          0.000000
fare           0.000000
embarked       0.002245
class          0.000000
who            0.000000
adult_male     0.000000
deck           0.772166
embark_town    0.002245
alive          0.000000
alone          0.000000
dtype: float64

In [96]:
def GetPRN(x):
    return (pd.isnull(x).sum()) / x.size
df.apply(GetPRN)

survived       0.000000
pclass         0.000000
sex            0.000000
age            0.198653
sibsp          0.000000
parch          0.000000
fare           0.000000
embarked       0.002245
class          0.000000
who            0.000000
adult_male     0.000000
deck           0.772166
embark_town    0.002245
alive          0.000000
alone          0.000000
dtype: float64

In [97]:
getNANP_2 = lambda x : ((pd.isnull(x).sum()) / len(x)) * 100
df.apply(getNANP_2)

survived        0.000000
pclass          0.000000
sex             0.000000
age            19.865320
sibsp           0.000000
parch           0.000000
fare            0.000000
embarked        0.224467
class           0.000000
who             0.000000
adult_male      0.000000
deck           77.216611
embark_town     0.224467
alive           0.000000
alone           0.000000
dtype: float64

In [100]:
notNAN = lambda x : (1-(pd.isnull(x).sum() / len(x)))
df.apply(notNAN)

survived       1.000000
pclass         1.000000
sex            1.000000
age            0.801347
sibsp          1.000000
parch          1.000000
fare           1.000000
embarked       0.997755
class          1.000000
who            1.000000
adult_male     1.000000
deck           0.227834
embark_town    0.997755
alive          1.000000
alone          1.000000
dtype: float64

In [102]:
nonNANP = lambda x : (1-(pd.isnull(x).sum() / len(x))) * 100
df.apply(nonNANP)

survived       100.000000
pclass         100.000000
sex            100.000000
age             80.134680
sibsp          100.000000
parch          100.000000
fare           100.000000
embarked        99.775533
class          100.000000
who            100.000000
adult_male     100.000000
deck            22.783389
embark_town     99.775533
alive          100.000000
alone          100.000000
dtype: float64

In [103]:
df.apply(notNAN, axis = 1)

0      0.933333
1      1.000000
2      0.933333
3      1.000000
4      0.933333
         ...
886    0.933333
887    1.000000
888    0.866667
889    1.000000
890    0.933333
Length: 891, dtype: float64

In [105]:
countNAN = lambda x : pd.isnull(x).sum()
df['missing'] = df.apply(countNAN, axis = 1)

In [106]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,missing
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,1
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,0
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,1
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,0
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,1
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,0
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,2
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,0
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,1

In [107]:
df[df['missing'] >= 2].sample(100)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,missing
601,0,3,male,NaN,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True,2
126,0,3,male,NaN,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,2
454,0,3,male,NaN,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,2
653,1,3,female,NaN,0,0,7.8292,Q,Third,woman,False,NaN,Queenstown,yes,True,2
64,0,1,male,NaN,0,0,27.7208,C,First,man,True,NaN,Cherbourg,no,True,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
497,0,3,male,NaN,0,0,15.1000,S,Third,man,True,NaN,Southampton,no,True,2
639,0,3,male,NaN,1,0,16.1000,S,Third,man,True,NaN,Southampton,no,False,2
674,0,2,male,NaN,0,0,0.0000,S,Second,man,True,NaN,Southampton,no,True,2
611,0,3,male,NaN,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True,2
354,0,3,male,NaN,0,0,7.2250,C,Third,man,True,NaN,Cherbourg,no,True,2

In [108]:
df = pd.read_csv('../data/gapminder.tsv', sep='\t')
df

          country continent  year  lifeExp       pop   gdpPercap
0     Afghanistan      Asia  1952   28.801   8425333  779.445314
1     Afghanistan      Asia  1957   30.332   9240934  820.853030
2     Afghanistan      Asia  1962   31.997  10267083  853.100710
3     Afghanistan      Asia  1967   34.020  11537966  836.197138
4     Afghanistan      Asia  1972   36.088  13079460  739.981106
...           ...       ...   ...      ...       ...         ...
1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306
1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786
1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298

[1704 rows x 6 columns]

In [109]:
df['lifeExp'].mean()

59.474439366197174

In [110]:
df.groupby('year')['lifeExp'].mean()

year
1952    49.057620
1957    51.507401
1962    53.609249
1967    55.678290
1972    57.647386
1977    59.570157
1982    61.533197
1987    63.212613
1992    64.160338
1997    65.014676
2002    65.694923
2007    67.007423
Name: lifeExp, dtype: float64

In [111]:
df['year'].unique()

array([1952, 1957, 1962, 1967, 1972, 1977, 1982, 1987, 1992, 1997, 2002,
       2007], dtype=int64)

In [112]:
y_1952 = df[df['year'] == 1952]['lifeExp'].mean()
y_1957 = df[df['year'] == 1957]['lifeExp'].mean()
y_1962 = df[df['year'] == 1962]['lifeExp'].mean()
y_2007 = df[df['year'] == 2007]['lifeExp'].mean()

In [113]:
df = pd.DataFrame({
    'year' : [1952, 1957, 1962, 2007],
    "" : [y_1952, y_1957, y_1962, y_2007]
})

In [114]:
df

   year
0  1952  49.057620
1  1957  51.507401
2  1962  53.609249
3  2007  67.007423

In [115]:
def getMean(data):
    sum = 0
    for i in data:
        sum += i
    return sum / len(data)

In [118]:
df = pd.read_csv('../data/gapminder.tsv', sep='\t')

In [119]:
df.groupby('year').agg(getMean)

C:\Users\starl\AppData\Local\Temp\ipykernel_8596\423667373.py:1: FutureWarning: ['country', 'continent'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  df.groupby('year').agg(getMean)

        lifeExp           pop     gdpPercap
year
1952  49.057620  1.695040e+07   3725.276046
1957  51.507401  1.876341e+07   4299.408345
1962  53.609249  2.042101e+07   4725.812342
1967  55.678290  2.265830e+07   5483.653047
1972  57.647386  2.518998e+07   6770.082815
1977  59.570157  2.767638e+07   7313.166421
1982  61.533197  3.020730e+07   7518.901673
1987  63.212613  3.303857e+07   7900.920218
1992  64.160338  3.599092e+07   8158.608521
1997  65.014676  3.883947e+07   9090.175363
2002  65.694923  4.145759e+07   9917.848365
2007  67.007423  4.402122e+07  11680.071820

In [120]:
df.mean()

C:\Users\starl\AppData\Local\Temp\ipykernel_8596\3698961737.py:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.mean()

year         1.979500e+03
lifeExp      5.947444e+01
pop          2.960121e+07
gdpPercap    7.215327e+03
dtype: float64

In [121]:
df.groupby('year')['lifeExp'].agg(getMean)

year
1952    49.057620
1957    51.507401
1962    53.609249
1967    55.678290
1972    57.647386
1977    59.570157
1982    61.533197
1987    63.212613
1992    64.160338
1997    65.014676
2002    65.694923
2007    67.007423
Name: lifeExp, dtype: float64

In [122]:
df.groupby('year')['lifeExp'].mean()

year
1952    49.057620
1957    51.507401
1962    53.609249
1967    55.678290
1972    57.647386
1977    59.570157
1982    61.533197
1987    63.212613
1992    64.160338
1997    65.014676
2002    65.694923
2007    67.007423
Name: lifeExp, dtype: float64

In [124]:
def getMean2(data, n):
    sum = 0
    for i in data:
        sum += i
    return sum / len(data) - n

df.groupby('year')['lifeExp'].agg(getMean2, n=df['lifeExp'].mean())

year
1952   -10.416820
1957    -7.967038
1962    -5.865190
1967    -3.796150
1972    -1.827053
1977     0.095718
1982     2.058758
1987     3.738173
1992     4.685899
1997     5.540237
2002     6.220483
2007     7.532983
Name: lifeExp, dtype: float64

In [125]:
def getMean2(data, n):
    sum = 0
    for i in data:
        sum += i
    return (sum / len(data)) - n

df.groupby('year')['lifeExp'].agg(getMean2, n=df['lifeExp'].mean())

year
1952   -10.416820
1957    -7.967038
1962    -5.865190
1967    -3.796150
1972    -1.827053
1977     0.095718
1982     2.058758
1987     3.738173
1992     4.685899
1997     5.540237
2002     6.220483
2007     7.532983
Name: lifeExp, dtype: float64

In [127]:
import numpy as np

In [129]:
df.groupby('year')['lifeExp'].agg([np.count_nonzero, np.mean, np.std])

      count_nonzero       mean        std
year
1952            142  49.057620  12.225956
1957            142  51.507401  12.231286
1962            142  53.609249  12.097245
1967            142  55.678290  11.718858
1972            142  57.647386  11.381953
1977            142  59.570157  11.227229
1982            142  61.533197  10.770618
1987            142  63.212613  10.556285
1992            142  64.160338  11.227380
1997            142  65.014676  11.559439
2002            142  65.694923  12.279823
2007            142  67.007423  12.073021